In [32]:
final_model = finalize_model(tuned_knn)

In [30]:
predict_model(
    modelo_carregado, 
    data = novo_cliente
)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,prediction_label,prediction_score
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0.625

In [ ]:
modelo_carregado = load_model("models/churn_model_v1")

Transformation Pipeline and Model Successfully Loaded

In [28]:
save_model(tuned_knn, "models/churn_model_v1")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['SeniorCitizen', 'tenure',
                                              'MonthlyCharges'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False...
                                     transformer=TargetEncoder(cols=['customerID',
                                                                     'TotalCharges'],
                                                               drop_invariant=False,
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               hierarchy=None,
                                                               min_samples_leaf=20,
                                                               return_df=True,
                                                               smoothing=10,
                                                               verbose=0))),
                 ('trained_model',
                  KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                       metric='manhattan', metric_params=None,
                                       n_jobs=-1, n_neighbors=16, p=2,
                                       weights='uniform'))],
          verbose=False),
 'models/churn_model_v1.pkl')

In [27]:
import os

os.makedirs("models", exist_ok = True)

In [26]:
predict_model(
    tuned_knn,
    data = novo_cliente
)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,prediction_label,prediction_score
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0.625

In [25]:
novo_cliente = df.drop(columns=["Churn"]).iloc[[0]]

In [24]:
predictions.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,prediction_label,prediction_score
2937,5312-IRCFR,Female,0,Yes,Yes,64,Yes,Yes,Fiber optic,No,...,No,Yes,One year,Yes,Electronic check,92.849998,5980.75,No,No,0.9375
3276,4210-QFJMF,Female,0,No,No,4,Yes,No,Fiber optic,No,...,No,Yes,Month-to-month,Yes,Electronic check,79.150002,317.25,Yes,Yes,0.9375
4374,2718-YSKCS,Male,0,Yes,Yes,71,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),19.600000,1387.45,No,No,1.0000
4375,9896-UYMIE,Male,0,No,No,66,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Bank transfer (automatic),114.300003,7383.7,No,No,0.8750
237,9903-LYSAB,Male,0,Yes,No,18,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,73.150002,1305.95,No,No,0.5625
213,4709-LKHYG,Female,0,Yes,Yes,29,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Electronic check,20.000000,540.05,No,No,1.0000
91,2424-WVHPL,Male,1,No,No,1,Yes,No,Fiber optic,No,...,No,No,Month-to-month,No,Electronic check,74.699997,74.7,No,Yes,0.6875
6523,2834-JKOOW,Female,0,No,No,15,No,No phone service,DSL,Yes,...,No,No,One year,No,Mailed check,45.900002,693.45,No,No,1.0000
5795,7048-GXDAY,Male,0,No,No,39,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Month-to-month,Yes,Electronic check,106.400002,4040.65,No,Yes,0.5625
5892,2709-UQGNP,Male,0,No,No,10,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,51.650002,524.5,No,No,0.8125

In [22]:
predictions = predict_model(tuned_knn)

In [21]:
print(knn)
print(tuned_knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=-1, n_neighbors=16, p=2,
                     weights='uniform')

In [20]:
tuned_knn = tune_model(knn)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [19]:
evaluate_model(knn)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [18]:
knn = create_model(best_model)

In [17]:
best_model = compare_models()

In [16]:
clf = setup(
    data = df,
    target = "Churn",
    session_id = 123
)

In [15]:
from pycaret.classification import *

In [14]:
df["TotalCharges"].value_counts().head()

TotalCharges
         11
20.2     11
19.75     9
20.05     8
19.9      8
Name: count, dtype: int64

In [13]:
df["TotalCharges"].dtype

dtype('O')

In [12]:
# Ver se tem algum valor nulo na planilha
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [11]:
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [9]:
df.shape

(7043, 21)

In [8]:
import pandas as pd

df = pd.read_csv("../data/Telco-Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
import pycaret

print(pycaret.__version__)

3.3.2

In [6]:
import sys

print(sys.version)

3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]